### PR TITLE
[WIP] automated releases

### PR DESCRIPTION
**Pull request by zeke**
This module self-updated for a while, but npm tightened up their downloads service and it now issues 409s if too many parallel requests are made.

This PR is a refactor to store the data in local files, bring in a throttling technique, and the build process now updates only a subset of the packages on each run, choosing a batch of the most-out-of-date files for update.

cc @kikobeats

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hey, can you comment the file with the real change? it's hard to find

**Comment by zeke** [comment]
Yeah that diff is huge!

https://github.com/nice-registry/download-counts/blob/439b1a5a8eb908714a3a4802ac177529b9b3fb4b/script/collect.js

**Comment by Kikobeats** [comment]
wow, nice idea! `Bottleneck`dependecy is very great.

I think you are trying to avoid streams, but I feel is the right way to load this big file; `all-the-package-names` will be tends to be even more bigger, so the bootstapping time for initialize this process will be bigger as well.

**Comment by zeke** [comment]
> I think you are trying to avoid streams

You caught me! Streams are very confusing to me. I've read all the docs, tried the "mississippi" techniques, but it hasn't clicked for me yet.

**Comment by Kikobeats** [comment]
Yes, streams are confusing and they have different implementations around NodeJS API. For understand better why we use stream modules instead of NodeJS API I recommend you [read this fantastic blogpost about that](https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html).

I think [mississippi](https://github.com/maxogden/mississippi) collect the best from the community. Also [Stream handbook by substack](https://github.com/substack/stream-handbook) is a recommended read.

About the PR, this is definetly better than the current codebase, so we can merge it and in the future try to improve using streams (and practice! 😄) .

**Comment by Kikobeats** [comment]
awesome!

**Comment by zeke** [comment]
Working on getting a new release out and making sure the Heroku setup still works.

**Comment by zeke** [comment]
```
~/git/nice-registry/download-counts master 6s
$ np minor --yolo
 ✔ Prerequisite check
 ✔ Git
 ✔ Bumping version using Yarn
 ✔ Publishing package
 ✔ Pushing tags

 download-counts 1.81.0 published 🎉
```

**Comment by zeke** [comment]
```
$ git push heroku master
Counting objects: 9339, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (265/265), done.
Writing objects: 100% (9339/9339), 167.62 MiB | 668.00 KiB/s, done.
Total 9339 (delta 258), reused 9326 (delta 249)
remote: 
remote: !	Size of checkout and restored submodules exceeds 1 GB. Reduce size and try pushing again.
remote: 
To https://git.heroku.com/npm-download-counts.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/npm-download-counts.git'

~/git/nice-registry/download-counts master 4m 44s
$ du -hs data
2.1G	data
```

Welp.. back to the drawing board.

**Comment by zeke** [comment]
Maybe tarballing is the answer:

```
$ du -hs data    
2.1G	data

$ tar cfz data.tgz data

$ du -hs data.tgz 
 10M	data.tgz
```

**Pull request merged**
